B 10
gorvan/PetHome pull request #10
Opened 2024-08-24 17:11 UTC by gorvan

2024-08-24 18:05 UTC, YADARAN1 requested changes

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.API/Extensions/ResponseExtensions.cs
> +        private static int GetStatusCode(ErrorType errorType)
В методе GetStatusCode, в строке ErrorType.Validtion, слово "Validation" написано с ошибкой

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Application/Volunteers/CreateVolunteer/CreateVolunteerHandler.cs
> +                return Errors.Volunteer.AlreadyExist();
В хендлерах у нас сборка, мы не должны делать проверку на IsFailure, т.к. они уже у нас провалидированы в другом месте и они УЖЕ пришли провалидированными и попали сюда + у тебя тут написано IsSuccess

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Application/Volunteers/CreateVolunteer/CreateVolunteerHandler.cs
> +                return Errors.Volunteer.AlreadyExist();
Поэтому всю проверку с хендлеров убрать

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/PetManadgement/ValueObjects/PetRequisites.cs
> +        public PetRequisites(IEnumerable<Requisite> requisites)
Конструктор должен быть приватным

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/PetManadgement/ValueObjects/PetRequisites.cs
> +        public PetRequisites() { }
нам для VO не нужно 2 конструктора, удалить

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/PetManadgement/ValueObjects/SocialNetworks.cs
> +        public SocialNetworks(IEnumerable<SocialNetwork> socialNets)
Тоже самое

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/PetManadgement/ValueObjects/SocialNetworks.cs
> +            SocialNets = socialNets.ToList();
переменные лучше назвать целиком, без сокращений

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/Shared/DateValue.cs
> +            if (date == DateTime.MinValue
можно сделать по другому (date < new DateTime(1900, 1, 1) || date > DateTime.Now)

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/Shared/Errors.cs
> +            public static Error AlreadyExist()
AlreadyExist можно засунуть в General

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Domain/SpeciesManagement/AggregateRoot/SpeciesBreedValue.cs
> +        public SpeciesBreedValue(SpeciesId speciesId, BreedId breedId)
обратно на приватный

2024-08-24 18:05 UTC, YADARAN1 commented on backend/src/PetHome.Infrastructure/Repositories/VolunteersRepository.cs
> +            if (volunteer == null)
лучше сначала сделать проверку, а потом уже делать запрос

2024-08-26 08:37 UTC, KirillSachkov approved these changes

2024-08-26 08:41 UTC, merged